import { Preset } from "../types/mock";

export const PRESETS: Preset[] = [
  {
    name: "Personnalisé",
    description: "Créez votre propre configuration de champs",
    fields: [],
  },
  {
    name: "MERN Stack Developer",
    description: "Profils de développeurs MERN Stack",
    fields: [
      { name: "id", type: "uuid" },
      { name: "name", type: "string" },
      { name: "email", type: "email" },
      { name: "techStack", type: "arrayMern" },
      { name: "yearsExperience", type: "number" },
      { name: "github", type: "github" },
    ],
  },
  {
    name: "E-commerce Product",
    description: "Produits pour boutique en ligne",
    fields: [
      { name: "id", type: "uuid" },
      { name: "title", type: "productName" },
      { name: "description", type: "description" },
      { name: "price", type: "price" },
      { name: "currency", type: "currency" },
      { name: "stock", type: "stock" },
      { name: "category", type: "category" },
      { name: "image", type: "imageUrl" },
      { name: "rating", type: "rating" },
    ],
  },
  {
    name: "Social Media Post",
    description: "Publications pour réseaux sociaux",
    fields: [
      { name: "id", type: "uuid" },
      { name: "author", type: "author" },
      { name: "avatar", type: "avatar" },
      { name: "content", type: "lorem" },
      { name: "image", type: "imageUrl" },
      { name: "likes", type: "likes" },
      { name: "comments", type: "comments" },
      { name: "createdAt", type: "createdAt" },
    ],
  },
  {
    name: "Blog Article",
    description: "Articles de blog complets",
    fields: [
      { name: "id", type: "uuid" },
      { name: "title", type: "title" },
      { name: "slug", type: "slug" },
      { name: "excerpt", type: "excerpt" },
      { name: "content", type: "loremLong" },
      { name: "author", type: "author" },
      { name: "publishedAt", type: "publishedAt" },
      { name: "tags", type: "tags" },
      { name: "readTime", type: "readTime" },
    ],
  },
  {
    name: "SaaS User",
    description: "Utilisateurs SaaS avec abonnements",
    fields: [
      { name: "id", type: "uuid" },
      { name: "name", type: "string" },
      { name: "email", type: "email" },
      { name: "company", type: "company" },
      { name: "plan", type: "plan" },
      { name: "mrr", type: "mrr" },
      { name: "status", type: "status" },
      { name: "joinedAt", type: "joinedAt" },
    ],
  },
  {
    name: "Todo App",
    description: "Tâches pour application Todo",
    fields: [
      { name: "id", type: "uuid" },
      { name: "title", type: "todoTitle" },
      { name: "completed", type: "completed" },
      { name: "priority", type: "priority" },
      { name: "dueDate", type: "dueDate" },
      { name: "createdAt", type: "createdAt" },
    ],
  },
  {
    name: "Restaurant Menu",
    description: "Plats pour menu de restaurant",
    fields: [
      { name: "id", type: "uuid" },
      { name: "name", type: "dishName" },
      { name: "description", type: "description" },
      { name: "price", type: "price" },
      { name: "category", type: "foodCategory" },
      { name: "calories", type: "calories" },
      { name: "vegetarian", type: "vegetarian" },
      { name: "image", type: "imageUrl" },
    ],
  },
];
